name: stager_example
description: Demonstrates the Stager package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  mockito: ^5.3.2
  provider: ^6.0.5
  stager:
    git:
      url: git@github.com:bryanoltman/stager.git
      ref: main

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  stager:
    path: ../

flutter:
  uses-material-design: true
